[tool]
[tool.commitizen]
name = "cz_conventional_commits"
version = "1.0.1"
tag_format = "v$major.$minor.$patch"
gpg_sign = true
version_files = ["Cargo.toml"]
update_changelog_on_bump = true
changelog_incremental = true
