[tool]
[tool.commitizen]
name = "cz_conventional_commits"
version = "0.1.0"
tag_format = "v$version"
gpg_sign = true
version_files = ["Cargo.toml"]
update_changelog_on_bump = true
changelog_incremental = true
