branches:
  - +([0-9])?(.{+([0-9]),x}).x
  - main
  - name: beta
    prerelease: true
  - name: alpha
    prerelease: true

plugins:
    - '@semantic-release/commit-analyzer'
    - '@semantic-release/release-notes-generator'
    - '@semantic-release/github'
    - - '@semantic-release/exec'
      - verifyConditionsCmd: "~/.cargo/bin/semantic-release-cargo verify-conditions"
        generateNotes: "cz bump --files-only"
        prepareCmd: "~/.cargo/bin/semantic-release-cargo prepare ${nextRelease.version}"
        publishCmd: "~/.cargo/bin/semantic-release-cargo publish"
    - - '@semantic-release/git'
      - assets: Cargo.toml Cargo.lock
