# SPDX-FileCopyrightText: 2023 - Ali Sajid Imami
#
# SPDX-License-Identifier: CC0-1.0

[tools]
rust = { version = "1.94.1", profile = "default", components = "rust-analyzer,llvm-tools,rust-src" }
python = "3.13"
jq = "1.8"
"cargo:bacon" = "3.22.0"
"cargo:cargo-about" = "0.8.4"
"cargo:cargo-audit" = "0.22.1"
hk = "1.41.1"
pkl = "0.31.1"
"cargo:cargo-toml-lint" = "0.1.1"
cocogitto = "7.0.0"
gitleaks = "8.30.1"
mdbook = "0.5.2"
"pipx:reuse" = "6.2.0"
"pipx:texthooks" = "0.7.1"
taplo = "0.10.0"
vale = "3.14.1"
yamllint = "1.38.0"
"cargo:cargo-edit" = "0.13.9"
"aqua:nextest-rs/nextest/cargo-nextest" = "0.9.132"
"aqua:taiki-e/cargo-llvm-cov" = "0.8.5"
markdownlint-cli2 = "0.22.0"
"aqua:EmbarkStudios/cargo-deny" = "0.19.1"
"aqua:rustsec/rustsec/cargo-audit" = "0.22.1"
"aqua:cross-rs/cross" = "0.2.5"

[env]
'_'.file = { path = ".env" }
