
# cargo-vet config file

[cargo-vet]
version = "0.5"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.chromeos]
url = "https://chromium.googlesource.com/chromiumos/third_party/rust_crates/+/main/cargo-vet/audits.toml?format=TEXT"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[policy.iptmnet]
audit-as-crates-io = true

[[exemptions.addr2line]]
version = "0.19.0"
criteria = "safe-to-deploy"

[[exemptions.adler]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.bytes]]
version = "1.2.1"
criteria = "safe-to-deploy"

[[exemptions.chrono]]
version = "0.4.22"
criteria = "safe-to-deploy"

[[exemptions.clap]]
version = "4.1.4"
criteria = "safe-to-deploy"

[[exemptions.clap_derive]]
version = "4.1.0"
criteria = "safe-to-deploy"

[[exemptions.clap_lex]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.core-foundation]]
version = "0.9.3"
criteria = "safe-to-deploy"

[[exemptions.core-foundation-sys]]
version = "0.8.3"
criteria = "safe-to-deploy"

[[exemptions.errno]]
version = "0.2.8"
criteria = "safe-to-deploy"

[[exemptions.errno-dragonfly]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.foreign-types]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.foreign-types-shared]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.futures-channel]]
version = "0.3.23"
criteria = "safe-to-deploy"

[[exemptions.futures-core]]
version = "0.3.23"
criteria = "safe-to-deploy"

[[exemptions.futures-sink]]
version = "0.3.23"
criteria = "safe-to-deploy"

[[exemptions.futures-task]]
version = "0.3.23"
criteria = "safe-to-deploy"

[[exemptions.futures-util]]
version = "0.3.23"
criteria = "safe-to-deploy"

[[exemptions.gimli]]
version = "0.27.1"
criteria = "safe-to-deploy"

[[exemptions.h2]]
version = "0.3.14"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.1.19"
criteria = "safe-to-deploy"

[[exemptions.http]]
version = "0.2.8"
criteria = "safe-to-deploy"

[[exemptions.http-body]]
version = "0.4.5"
criteria = "safe-to-deploy"

[[exemptions.httparse]]
version = "1.7.1"
criteria = "safe-to-deploy"

[[exemptions.httpdate]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.hyper]]
version = "0.14.20"
criteria = "safe-to-deploy"

[[exemptions.hyper-tls]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.iana-time-zone]]
version = "0.1.47"
criteria = "safe-to-deploy"

[[exemptions.indexmap]]
version = "1.9.1"
criteria = "safe-to-deploy"

[[exemptions.instant]]
version = "0.1.12"
criteria = "safe-to-deploy"

[[exemptions.ipnet]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.iptmnet]]
version = "1.7.1"
criteria = "safe-to-deploy"

[[exemptions.itoa]]
version = "1.0.3"
criteria = "safe-to-deploy"

[[exemptions.js-sys]]
version = "0.3.59"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.139"
criteria = "safe-to-deploy"

[[exemptions.lock_api]]
version = "0.4.7"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.mime]]
version = "0.3.16"
criteria = "safe-to-deploy"

[[exemptions.miniz_oxide]]
version = "0.6.2"
criteria = "safe-to-deploy"

[[exemptions.mio]]
version = "0.8.4"
criteria = "safe-to-deploy"

[[exemptions.native-tls]]
version = "0.2.10"
criteria = "safe-to-deploy"

[[exemptions.num_cpus]]
version = "1.13.1"
criteria = "safe-to-deploy"

[[exemptions.object]]
version = "0.30.3"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.13.1"
criteria = "safe-to-deploy"

[[exemptions.openssl]]
version = "0.10.41"
criteria = "safe-to-deploy"

[[exemptions.openssl-macros]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.openssl-probe]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.openssl-sys]]
version = "0.9.75"
criteria = "safe-to-deploy"

[[exemptions.os_str_bytes]]
version = "6.3.0"
criteria = "safe-to-deploy"

[[exemptions.parking_lot]]
version = "0.12.1"
criteria = "safe-to-deploy"

[[exemptions.parking_lot_core]]
version = "0.9.3"
criteria = "safe-to-deploy"

[[exemptions.pin-project-lite]]
version = "0.2.9"
criteria = "safe-to-deploy"

[[exemptions.pin-utils]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.pkg-config]]
version = "0.3.25"
criteria = "safe-to-deploy"

[[exemptions.proc-macro-error]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.proc-macro-error-attr]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.remove_dir_all]]
version = "0.5.3"
criteria = "safe-to-deploy"

[[exemptions.reqwest]]
version = "0.11.14"
criteria = "safe-to-deploy"

[[exemptions.ryu]]
version = "1.0.11"
criteria = "safe-to-deploy"

[[exemptions.schannel]]
version = "0.1.20"
criteria = "safe-to-deploy"

[[exemptions.scopeguard]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.security-framework]]
version = "2.7.0"
criteria = "safe-to-deploy"

[[exemptions.security-framework-sys]]
version = "2.6.1"
criteria = "safe-to-deploy"

[[exemptions.serde]]
version = "1.0.144"
criteria = "safe-to-deploy"

[[exemptions.serde-aux]]
version = "4.0.0"
criteria = "safe-to-deploy"

[[exemptions.serde_derive]]
version = "1.0.144"
criteria = "safe-to-deploy"

[[exemptions.serde_json]]
version = "1.0.85"
criteria = "safe-to-deploy"

[[exemptions.serde_urlencoded]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.signal-hook-registry]]
version = "1.4.0"
criteria = "safe-to-deploy"

[[exemptions.slab]]
version = "0.4.7"
criteria = "safe-to-deploy"

[[exemptions.smallvec]]
version = "1.9.0"
criteria = "safe-to-deploy"

[[exemptions.socket2]]
version = "0.4.6"
criteria = "safe-to-deploy"

[[exemptions.strsim]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "1.0.99"
criteria = "safe-to-deploy"

[[exemptions.tempfile]]
version = "3.3.0"
criteria = "safe-to-deploy"

[[exemptions.termcolor]]
version = "1.1.3"
criteria = "safe-to-deploy"

[[exemptions.terminal_size]]
version = "0.2.3"
criteria = "safe-to-deploy"

[[exemptions.tokio]]
version = "1.24.2"
criteria = "safe-to-deploy"

[[exemptions.tokio-macros]]
version = "1.8.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-native-tls]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-util]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.tower-service]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.tracing]]
version = "0.1.36"
criteria = "safe-to-deploy"

[[exemptions.tracing-core]]
version = "0.1.29"
criteria = "safe-to-deploy"

[[exemptions.try-lock]]
version = "0.2.3"
criteria = "safe-to-deploy"

[[exemptions.unicode-width]]
version = "0.1.10"
criteria = "safe-to-deploy"

[[exemptions.vcpkg]]
version = "0.2.15"
criteria = "safe-to-deploy"

[[exemptions.want]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.11.0+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen]]
version = "0.2.82"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-backend]]
version = "0.2.82"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-futures]]
version = "0.4.32"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.82"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.82"
criteria = "safe-to-deploy"

[[exemptions.web-sys]]
version = "0.3.59"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-util]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winreg]]
version = "0.10.1"
criteria = "safe-to-deploy"
