on:
  workflow_call:
    outputs:
      new_version:
        description: 'The new version to release'
        value: ${{ jobs.semantic.outputs.new_release_version }}
      new_release_published:
        description: 'Whether a new release was published'
        value: ${{ jobs.semantic.outputs.new_release_published }}

name: Semantic Release

env:
  RUST_BACKTRACE: 1
  SEMREL_RUST_VERSION: 2.1.15


jobs:
    release:
        name: Semantic Release
        runs-on: ubuntu-latest
        outputs:
          release_version: ${{steps.semantic.outputs.new_release_version}}
          new_release: ${{steps.semantic.outputs.new_release_published}}
          github_event_data: ${{ steps.payload.outputs.github_event_data }}
        steps:
          - name: Checkout
            uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
            with:
                fetch-depth: 0
                persist-credentials: false

          - name: Save Event Payload
            id: payload
            run: |
              echo "::set-output name=github_event_data::$(cat $GITHUB_EVENT_PATH | base64)"

          - name: Install Python
            uses: actions/setup-python@v4
            with:
              python-version: '3.10'

          - name: install commitizen
            run: pip install -U commitizen

          - name: Install Rust Stable
            uses: actions-rs/toolchain@v1
            with:
                profile: minimal
                toolchain: stable
                override: true

          # The release build is used in the Semantic Release step
          - name: Build
            uses: actions-rs/cargo@v1
            with:
                command: build
                args: --release

          - name: Install Semantic Release Cargo
            run: cargo install semantic-release-cargo --version ${{ env.SEMREL_RUST_VERSION }}

          - name: Semantic Release
            uses: cycjimmy/semantic-release-action@v2
            id: semantic
            with:
                semantic_version: 17.1.1
                extra_plugins: |
                    @semantic-release/exec@5.0
                    @semantic-release/git@9.0
            env:
                GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT_GITHUB }}
                CARGO_REGISTRY_TOKEN: ${{ secrets.SEMREL_CRATES_IO }}
