on:
  release:
    types: [published]


name: Release

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
            platform: windows_x86_64
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.bz2 tar.xz
            platform: linux_x86_64
          - target: x86_64-apple-darwin
            archive: zip
            platform: macos_x86_64
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          MINIFY: true
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
          ARCHIVE_NAME: IPTMNet-CLI-${{ github.event.release.tag_name }}-${{matrix.platform}}
          EXTRA_FILES: "README.md LICENSE"
